# Changes here will be overwritten by Copier
_commit: v5.0.2
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-number-conversion
project_description: Convert numbers between binary, octal, decimal and hexadecimal
    representation.
project_slug: number-conversion
pypi: true

