# Changes here will be overwritten by Copier
_commit: v3.4.1
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
project_description: This Trasform plugin is used to convert numbers from one base
    to another base
project_slug: number-conversion

